import 'package:flutter/material.dart';
import 'package:myapp/shared/components.dart';

class MarineEnergyScreen extends StatefulWidget {
  const MarineEnergyScreen({Key? key}) : super(key: key);

  @override
  _MarineEnergyScreenState createState() => _MarineEnergyScreenState();
}

class _MarineEnergyScreenState extends State<MarineEnergyScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: defultText(text: 'Marine Energy'),
      ),
      body: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        physics: BouncingScrollPhysics(),
        child: Padding(
          padding: const EdgeInsets.all(10.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              defultImage(url: 'https://media.istockphoto.com/photos/pipelines-on-ocean-bottom-underwater-3d-rendering-picture-id1098052874?b=1&k=20&m=1098052874&s=170667a&w=0&h=cwoCsEAtM-VO4SHRsdqp2Xm9WmMc1hb1nV3OAmHhHkY='),
              Center(child: defultTitleText(titleText: 'Marine Energy:')),
              defultParagraphText(paragraphText: 'It is the energy generated by ocean waves, tidal phenomena, water salinity, or water temperature differences. As a result of the movement of water in the world\'s oceans, a huge amount of kinetic energy is generated, which can be used to generate electricity used either in homes, transportation, and factories'),
              defultParagraphText(paragraphText: 'Sea currents are generated as a result of winds, differences in temperature, salinity, water depth, and Earth\'s rotation. The sun is the main driving force for the movement of waves.'),
              defultParagraphText(paragraphText: 'Because the wave speed is almost constant (there are no big changes in the wave speed), and the direction of the wave is constant, turbines are used to generate electric power.'),
              defultParagraphText(paragraphText: 'Ocean currents are used as an important tool in determining the climate in most regions of the world.'),
              Center(child: defultTitleText(titleText: 'Usage:')),
              defultParagraphText(paragraphText: 'Use of marine energy in some places resulting from burning coal and oil; that move it. Rotating turbines with  electricity . And we can use tidal power to power homes and businesses. We can use tidal power in some places. Instead of burning coal and oil that contribute to global warming, tidal generators (or turbines) work like wind turbines, except that ocean currents,  And  it\'s not the wind, it\'s moving it. The rotating turbine is connected to another device that produces electricity, the electricity then travels through wires to a city that people need.'),
              defultParagraphText(paragraphText: 'Tidal energy was used in mechanical crushing of grain in grain mills, turbine movement due to tidal energy was used in crushing grain, however, with the advent of fossil fuels, the use of tidal energy became very low.'),
              defultImage(url: 'https://media.istockphoto.com/photos/large-transport-ship-and-view-of-the-harbor-picture-id1095827258?b=1&k=20&m=1095827258&s=170667a&w=0&h=MLD1WzbVaJKa7ycMF9gpT_5nFpl7SX3CPCeqmGfA7W4='),
              defultParagraphText(paragraphText: 'Tidal energy can also be used as energy storage, one of the uses of hydropower like many hydroelectric dams can be used to store large energy, so tidal barrages can be modified with their tanks to store energy. Although this has not been tried, with appropriate modifications tidal energy can also be stored although costs can be high.'),
              Center(child: defultTitleText(titleText: 'The advantages:')),
              defultParagraphText(paragraphText: 'Environment-friendly energy source: Wave energy does not emit greenhouse gasses when generated, as fossil fuels do. The turbines generate electricity through the power of waves, making them pollution-free, renewable energy sources. With the advancement of technology, tidal power can be a massive part of the green energy mix, complementing solar power, wind turbines, geothermal, and hydropower.'),
              defultParagraphText(paragraphText: '1.	Renewable source of energy: Like all alternative energy sources, wave power is renewable. Waves are created by wind, and the wind is caused by uneven heat on the planet’s surface, driven mainly by the sun warming at different rates at different locations. Wind moves the heat energy from one part of the planet to another, which causes waves to form. Because the wind will always exist, waves will always be available at the water’s surface to generate electricity, making this a renewable source.'),
              defultParagraphText(paragraphText: '2.	Reliable energy source: Waves are hardly interrupted and almost always in motion. This makes electricity generation from wave energy a more reliable energy source than wind power since wind is not constantly blowing. However, the amount of energy transported through waves does vary every year and from season to season.'),
              defultImage(url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmB2bCU3utMATkzhUsXxf4rY59Uw63wfZvZnpvI1I0t2ekI_vs-uYPu2fiRB5EO8Ezwnc&usqp=CAU'),
              defultParagraphText(paragraphText: '3.	Enormous energy potential: The quantity of kinetic energy exerted in a wave is enormous – that energy gets captured by wave energy converters to produce electricity. The ocean provides a lot of potential for energy production because it is constantly moving and generating energy. There is also potential because many countries have access to an ocean or a sea that can help power their electric grids.'),
              defultParagraphText(paragraphText: '4.	Less dependency on fossil fuels: Dependence on fossil fuels can be reduced if energy from wave power is extracted up to its maximum. This will help curb air .'),
              defultParagraphText(paragraphText: '5.	No damage to land: Unlike fossil fuels, which cause massive damage to land as they can leave large holes while extracting energy, wave power does not cause any damage to the earth. It is a safe, clean, and consistent method to produce energy from the ocean.'),
              Center(child: defultTitleText(titleText: 'Disadvantages of Wave Energy: ')),
              defultParagraphText(paragraphText: '1.	Environmental effects: Because wave energy is still developing, primarily in research, there is no measure of the environmental impacts of large-scale power stations on the shore. Establishing plants directly on the beach might be harmful because they would be unsightly and can cause damage to marine life and the surrounding ecosystems. Local fishing zones could also be affected, or the plants could cause more coastal corrosion.'),
              defultParagraphText(paragraphText: '2.	Highly expensive: Wave power is an energy technology in the early stages of development, making speculating on prices difficult. Currently, the prices of wave power are generally very high because they are in the research phase of development, but the prices can go down in the future. At the moment, no energy company is utilizing wave energy at a large scale, which would bring the cost down.'),
              defultImage(url: 'https://www.marineinsight.com/wp-content/uploads/2021/01/Bombora-And-MOL-Forge-Partnership-To-Identify-Marine-Energy-Project-Opportunities-In-Japan-.png'),
              defultParagraphText(paragraphText: '3.	High maintenance costs: Maintenance for these plants is estimated to be very expensive because they will be submerged in constantly moving saltwater. The constant movement can lead to more breaking. Wave energy plants will most probably need regular and costly maintenance.'),
              defultParagraphText(paragraphText: '4.	Hard to scale: The biggest drawback at the moment is that no utility can install wave farms as they are not yet large enough to produce a considerable amount of electricity. The technology is expected to grow, but it remains challenging to implement wave energy generators at a usable scale.'),
              Center(child: defultTitleText(titleText: 'The largest wind energy producing countries in the world:')),
              defultParagraphText(paragraphText: '1-China(188.2)'),
              defultParagraphText(paragraphText: '- The Global Council for Local Environmental Control has described the engine of global market growth over the past decade.'),
              defultParagraphText(paragraphText: '- China is the largest market for advice since 2009, and it boosted its soil in 19.7 GW during 2017.'),
              defultParagraphText(paragraphText: '2-United State(89.0)'),
              defultParagraphText(paragraphText: 'The US wind market has added over 7 GW of wind capacity.'),
              defultParagraphText(paragraphText: 'Texas remains the largest player in the industry in the country, with 22 gigawatts of wind capacity alone.'),
              defultParagraphText(paragraphText: 'Iowa provides 36% of its electricity needs through wind energy sources.'),
              defultParagraphText(paragraphText: '3-Germany(56.1)'),
              defultParagraphText(paragraphText: 'Germany ranks first in Europe in terms of the ability to generate electricity from wind resources.'),
              defultParagraphText(paragraphText: '- It alone added more than 6.5 GW of production capacity in 2017, an increase of 15% over the level recorded in 2016.'),
              defultParagraphText(paragraphText: '4-India(32.8)'),
              defultParagraphText(paragraphText: 'India had a record year in 2017, with over 4 GW of wind capacity added.'),
              defultParagraphText(paragraphText: 'The World Council report revealed that Asia as a whole was the world\'s largest regional market for adding more wind energy production capacity, a title it maintains for the ninth consecutive year.'),
              defultParagraphText(paragraphText: '5-Spain(23.1)'),
              defultImage(url: 'https://www.betterworld.bmnxt.com/wp-content/uploads/2019/08/Ocean-energy-declared-renewable-energy.jpg'),
              defultParagraphText(paragraphText: 'Although Wind Europe data reveals that Spain added only 96 megawatts of wind power in 2017, the country is a major player in this sector on the European stage.'),
              defultParagraphText(paragraphText: '6-United kingdom(18.8)'),
              defultParagraphText(paragraphText: 'The United Kingdom is known for its dominance in the field of offshore wind energy, and a report by the European Wind Association "Wind Europe" said that Britain is the largest home to offshore wind plants in the old continent.'),
              defultParagraphText(paragraphText: 'Overall, the UK added 4 GW of wind capacity in 2017, five times the level recorded in 2016.'),
              defultParagraphText(paragraphText: '7- France (13.7)'),
              defultParagraphText(paragraphText: '2017 was a remarkable year for the wind energy industry in France, as the country added 1.7 gigawatts of production capacity for onshore plants.'),
              defultParagraphText(paragraphText: 'Wind energy sources in France provide enough electricity to power 11 million   homes.'),
              defultParagraphText(paragraphText: '8- Brazil (12.7)'),
              defultParagraphText(paragraphText: 'Brazil added more than 2 gigawatts of wind energy capacity over the past year.'),
              defultParagraphText(paragraphText: 'In total, the number of workers in the wind energy industry by the end of 2017, reached about 190,000 workers and employees.'),
              defultParagraphText(paragraphText: 'Brazil is one of the countries with the best wind resources in the world.'),
              defultImage(url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqUIGb9ku7w9B54K2MPGv2RNMg23fXLVpKBhExBw9pcezUrxzddiW2XUnW2Uup924zOE0&usqp=CAU'),
              defultParagraphText(paragraphText: '9-Canada(12.2)'),
              defultParagraphText(paragraphText: 'With this level of production capacity, Canada has enough energy to meet the needs of more than 3 million homes, according to the Canadian Wind Energy Association.'),
              defultParagraphText(paragraphText: 'Ten projects were completed last year, providing a production capacity of 341 megawatts, and there are currently nearly 300 wind farms operating in Canada.'),
              defultParagraphText(paragraphText: 'Brazil is one of the countries with the best wind resources in the world.'),
              defultParagraphText(paragraphText: '10- Italy(9.4)'),
              defultParagraphText(paragraphText: 'The EU countries collectively have 168 GW of wind energy capacity (15.8 GW provided by offshore farms), and Italy contributes a modest amount, but enough to place it in the big five in Europe.'),
            ],
          ),
        ),
      ),
    );  }
}

